/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import java.awt.Image;
import java.lang.reflect.Array;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import logic.Alumno;
import logic.Modulo;

/**
 *
 * @author Reibax
 */
public class ShowStudent extends javax.swing.JDialog {

    /**
     * Creates new form ShowStudent
     */
    public ShowStudent(java.awt.Frame parent, boolean modal,ArrayList<Alumno> alumnos) {
        super(parent, modal);
        initComponents();
        this.alumnos=alumnos;
        listModel.removeAllElements();
    }
    ImageIcon img = new ImageIcon("src/main/java/img/lg.png");
    ArrayList<Alumno> alumnos = new ArrayList<>();  
    DefaultListModel<String> listModel = new DefaultListModel<>();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNameToFind = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        btnShowStudent = new javax.swing.JButton();
        pnlShowStudent = new javax.swing.JPanel();
        txtNameData = new javax.swing.JLabel();
        txtLocallidadData = new javax.swing.JLabel();
        txtHourData = new javax.swing.JLabel();
        txtShowName = new javax.swing.JTextField();
        txtShowLocalidad = new javax.swing.JTextField();
        txtShowHours = new javax.swing.JTextField();
        txtModulosData = new javax.swing.JLabel();
        pnlModulos = new javax.swing.JScrollPane();
        listModulos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Academia Mas");
        setFont(new java.awt.Font("Hack Nerd Font Mono", 1, 14)); // NOI18N
        setIconImage(img.getImage());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        txtNameToFind.setFont(new java.awt.Font("Hack Nerd Font Mono", 1, 12)); // NOI18N
        txtNameToFind.setText("Nombre a buscar:");

        btnShowStudent.setText("Mostrar");
        btnShowStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowStudentActionPerformed(evt);
            }
        });

        pnlShowStudent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hack Nerd Font Mono", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        txtNameData.setText("Nombre:");

        txtLocallidadData.setText("Localidad");

        txtHourData.setText("Horas:");

        txtShowName.setFont(new java.awt.Font("Hack Nerd Font Mono", 1, 14)); // NOI18N
        txtShowName.setForeground(new java.awt.Color(0, 0, 0));
        txtShowName.setToolTipText("");
        txtShowName.setCaretColor(new java.awt.Color(0, 0, 0));
        txtShowName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtShowName.setEnabled(false);
        txtShowName.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtShowName.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtShowName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShowNameActionPerformed(evt);
            }
        });
        txtShowName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtShowNamePropertyChange(evt);
            }
        });

        txtShowLocalidad.setFont(new java.awt.Font("Hack Nerd Font Mono", 1, 14)); // NOI18N
        txtShowLocalidad.setForeground(new java.awt.Color(0, 0, 0));
        txtShowLocalidad.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtShowLocalidad.setEnabled(false);
        txtShowLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShowLocalidadActionPerformed(evt);
            }
        });

        txtShowHours.setFont(new java.awt.Font("Hack Nerd Font Mono", 1, 14)); // NOI18N
        txtShowHours.setForeground(new java.awt.Color(0, 0, 0));
        txtShowHours.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtShowHours.setEnabled(false);

        javax.swing.GroupLayout pnlShowStudentLayout = new javax.swing.GroupLayout(pnlShowStudent);
        pnlShowStudent.setLayout(pnlShowStudentLayout);
        pnlShowStudentLayout.setHorizontalGroup(
            pnlShowStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlShowStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlShowStudentLayout.createSequentialGroup()
                        .addComponent(txtNameData)
                        .addGap(18, 18, 18)
                        .addComponent(txtShowName, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlShowStudentLayout.createSequentialGroup()
                        .addGroup(pnlShowStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLocallidadData)
                            .addComponent(txtHourData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlShowStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtShowHours, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(txtShowLocalidad))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlShowStudentLayout.setVerticalGroup(
            pnlShowStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowStudentLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlShowStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameData)
                    .addComponent(txtShowName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnlShowStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtShowLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocallidadData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlShowStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHourData)
                    .addComponent(txtShowHours, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtModulosData.setFont(new java.awt.Font("Hack Nerd Font Mono", 1, 12)); // NOI18N
        txtModulosData.setForeground(new java.awt.Color(0, 0, 0));
        txtModulosData.setText("Módulos");

        listModulos.setBackground(new java.awt.Color(255, 255, 255));
        listModulos.setFont(new java.awt.Font("Hack Nerd Font Mono", 1, 18)); // NOI18N
        listModulos.setForeground(new java.awt.Color(0, 0, 0));
        listModulos.setEnabled(false);
        listModulos.setSelectionBackground(new java.awt.Color(0, 0, 0));
        listModulos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        pnlModulos.setViewportView(listModulos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtModulosData)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNameToFind)
                                .addGap(18, 18, 18)
                                .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlShowStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(btnShowStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(txtModulosData))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameToFind, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnShowStudent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlShowStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtShowNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtShowNamePropertyChange
        
    }//GEN-LAST:event_txtShowNamePropertyChange

    private void btnShowStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowStudentActionPerformed
        listModel.removeAllElements();
        for (Alumno alumno : alumnos) {
            
            if(txtStudentName.getText().equalsIgnoreCase(alumno.getNombre())){
            System.out.println(alumno.toString());
            txtShowName.setText(alumno.getNombre());
            txtShowLocalidad.setText(alumno.getLocalidad());
            txtShowHours.setText(String.valueOf((int) alumno.getNumberHours()));
            listModulos.setModel(listModel);
            for (Modulo modulo : alumno.getModulosStudent()) {
                listModel.addElement(modulo.getNombre());
            }
            }
         
        }
        
    }//GEN-LAST:event_btnShowStudentActionPerformed

    private void txtShowNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShowNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShowNameActionPerformed

    private void txtShowLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShowLocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShowLocalidadActionPerformed

   

     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowStudent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JList<String> listModulos;
    private javax.swing.JScrollPane pnlModulos;
    private javax.swing.JPanel pnlShowStudent;
    private javax.swing.JLabel txtHourData;
    private javax.swing.JLabel txtLocallidadData;
    private javax.swing.JLabel txtModulosData;
    private javax.swing.JLabel txtNameData;
    private javax.swing.JLabel txtNameToFind;
    private javax.swing.JTextField txtShowHours;
    private javax.swing.JTextField txtShowLocalidad;
    private javax.swing.JTextField txtShowName;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}
